/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesUrbanRouteImport } from './routes/services/urban'
import { Route as ServicesProjectsRouteImport } from './routes/services/projects'
import { Route as ServicesEngineeringRouteImport } from './routes/services/engineering'
import { Route as ServicesConsultingRouteImport } from './routes/services/consulting'
import { Route as ServicesArchitectureRouteImport } from './routes/services/architecture'
import { Route as Services3dRouteImport } from './routes/services/3d'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as AdminProjectsNewRouteImport } from './routes/admin/projects/new'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as AdminProjectsProjectIdEditRouteImport } from './routes/admin/projects/$projectId/edit'
import { Route as AdminBlogPostIdEditRouteImport } from './routes/admin/blog/$postId/edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesUrbanRoute = ServicesUrbanRouteImport.update({
  id: '/services/urban',
  path: '/services/urban',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProjectsRoute = ServicesProjectsRouteImport.update({
  id: '/services/projects',
  path: '/services/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEngineeringRoute = ServicesEngineeringRouteImport.update({
  id: '/services/engineering',
  path: '/services/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesConsultingRoute = ServicesConsultingRouteImport.update({
  id: '/services/consulting',
  path: '/services/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesArchitectureRoute = ServicesArchitectureRouteImport.update({
  id: '/services/architecture',
  path: '/services/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const Services3dRoute = Services3dRouteImport.update({
  id: '/services/3d',
  path: '/services/3d',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsProjectIdEditRoute =
  AdminProjectsProjectIdEditRouteImport.update({
    id: '/projects/$projectId/edit',
    path: '/projects/$projectId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBlogPostIdEditRoute = AdminBlogPostIdEditRouteImport.update({
  id: '/blog/$postId/edit',
  path: '/blog/$postId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/3d': typeof Services3dRoute
  '/services/architecture': typeof ServicesArchitectureRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/engineering': typeof ServicesEngineeringRoute
  '/services/projects': typeof ServicesProjectsRoute
  '/services/urban': typeof ServicesUrbanRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/blog/$postId/edit': typeof AdminBlogPostIdEditRoute
  '/admin/projects/$projectId/edit': typeof AdminProjectsProjectIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/3d': typeof Services3dRoute
  '/services/architecture': typeof ServicesArchitectureRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/engineering': typeof ServicesEngineeringRoute
  '/services/projects': typeof ServicesProjectsRoute
  '/services/urban': typeof ServicesUrbanRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/blog/$postId/edit': typeof AdminBlogPostIdEditRoute
  '/admin/projects/$projectId/edit': typeof AdminProjectsProjectIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/3d': typeof Services3dRoute
  '/services/architecture': typeof ServicesArchitectureRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/engineering': typeof ServicesEngineeringRoute
  '/services/projects': typeof ServicesProjectsRoute
  '/services/urban': typeof ServicesUrbanRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/blog/$postId/edit': typeof AdminBlogPostIdEditRoute
  '/admin/projects/$projectId/edit': typeof AdminProjectsProjectIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/blog/$slug'
    | '/demo/tanstack-query'
    | '/projects/$slug'
    | '/services/3d'
    | '/services/architecture'
    | '/services/consulting'
    | '/services/engineering'
    | '/services/projects'
    | '/services/urban'
    | '/admin/'
    | '/blog/'
    | '/projects/'
    | '/admin/blog/new'
    | '/admin/projects/new'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin/blog/'
    | '/admin/projects/'
    | '/admin/blog/$postId/edit'
    | '/admin/projects/$projectId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/privacy'
    | '/terms'
    | '/blog/$slug'
    | '/demo/tanstack-query'
    | '/projects/$slug'
    | '/services/3d'
    | '/services/architecture'
    | '/services/consulting'
    | '/services/engineering'
    | '/services/projects'
    | '/services/urban'
    | '/admin'
    | '/blog'
    | '/projects'
    | '/admin/blog/new'
    | '/admin/projects/new'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin/blog'
    | '/admin/projects'
    | '/admin/blog/$postId/edit'
    | '/admin/projects/$projectId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/blog/$slug'
    | '/demo/tanstack-query'
    | '/projects/$slug'
    | '/services/3d'
    | '/services/architecture'
    | '/services/consulting'
    | '/services/engineering'
    | '/services/projects'
    | '/services/urban'
    | '/admin/'
    | '/blog/'
    | '/projects/'
    | '/admin/blog/new'
    | '/admin/projects/new'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin/blog/'
    | '/admin/projects/'
    | '/admin/blog/$postId/edit'
    | '/admin/projects/$projectId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  Services3dRoute: typeof Services3dRoute
  ServicesArchitectureRoute: typeof ServicesArchitectureRoute
  ServicesConsultingRoute: typeof ServicesConsultingRoute
  ServicesEngineeringRoute: typeof ServicesEngineeringRoute
  ServicesProjectsRoute: typeof ServicesProjectsRoute
  ServicesUrbanRoute: typeof ServicesUrbanRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/urban': {
      id: '/services/urban'
      path: '/services/urban'
      fullPath: '/services/urban'
      preLoaderRoute: typeof ServicesUrbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/projects': {
      id: '/services/projects'
      path: '/services/projects'
      fullPath: '/services/projects'
      preLoaderRoute: typeof ServicesProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/engineering': {
      id: '/services/engineering'
      path: '/services/engineering'
      fullPath: '/services/engineering'
      preLoaderRoute: typeof ServicesEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/consulting': {
      id: '/services/consulting'
      path: '/services/consulting'
      fullPath: '/services/consulting'
      preLoaderRoute: typeof ServicesConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/architecture': {
      id: '/services/architecture'
      path: '/services/architecture'
      fullPath: '/services/architecture'
      preLoaderRoute: typeof ServicesArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/3d': {
      id: '/services/3d'
      path: '/services/3d'
      fullPath: '/services/3d'
      preLoaderRoute: typeof Services3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/$projectId/edit': {
      id: '/admin/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/admin/projects/$projectId/edit'
      preLoaderRoute: typeof AdminProjectsProjectIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$postId/edit': {
      id: '/admin/blog/$postId/edit'
      path: '/blog/$postId/edit'
      fullPath: '/admin/blog/$postId/edit'
      preLoaderRoute: typeof AdminBlogPostIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminBlogPostIdEditRoute: typeof AdminBlogPostIdEditRoute
  AdminProjectsProjectIdEditRoute: typeof AdminProjectsProjectIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminBlogPostIdEditRoute: AdminBlogPostIdEditRoute,
  AdminProjectsProjectIdEditRoute: AdminProjectsProjectIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  Services3dRoute: Services3dRoute,
  ServicesArchitectureRoute: ServicesArchitectureRoute,
  ServicesConsultingRoute: ServicesConsultingRoute,
  ServicesEngineeringRoute: ServicesEngineeringRoute,
  ServicesProjectsRoute: ServicesProjectsRoute,
  ServicesUrbanRoute: ServicesUrbanRoute,
  BlogIndexRoute: BlogIndexRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
